#+title: rime package readme
#+author: vanniuner
#+SETUPFILE: ~/.doom.d/org-head.setup


* Use system input rime 
Use system input method get a more unify experience, the control chain like  C-; -hammerspoon-> shift space -> switch rime ascii.
** evil hook
#+begin_src lisp
(defun my/mac-switch-to-english ()
  "切换到系统英文输入法"
  (call-process "macism" nil 0 nil
                "com.apple.keylayout.ABC"))

(defun my/mac-switch-to-chinese ()
  "切换到系统中文输入法（Squirrel / Rime）"
  (call-process "macism" nil 0 nil
                "im.rime.inputmethod.Squirrel.Hans"))

(with-eval-after-load 'evil
  ;; 进入 insert → 中文
  (add-hook 'evil-insert-state-entry-hook
            #'my/mac-switch-to-chinese)

  ;; 退出 insert → 英文
  (add-hook 'evil-insert-state-exit-hook
            #'my/mac-switch-to-english))

#+end_src
** hammerspoon.config
#+begin_src lua
hs.hotkey.bind({"ctrl"}, ";", function()
    local win = hs.window.frontmostWindow()
    if win then
        local appName = win:application():name()
        if appName == "Emacs" then
            hs.eventtap.keyStroke({"shift"}, "space")
            -- hs.eventtap.keyStroke({"ctrl"}, "z")
        else
            hs.eventtap.keyStroke({"ctrl"}, "z")
        end
    end
end)
#+end_src
** install macism
#+begin_src shell
brew tap laishulu/homebrew
brew install macism
#+end_src

** rime keybinding config
#+begin_src yaml
# 快捷键
key_binder:
  bindings:
    # Tab / Shift+Tab 切换光标至下/上一个拼音
    #- { when: composing, accept: Shift+Tab, send: Shift+Left }
    #- { when: composing, accept: Tab, send: Shift+Right }
    # Tab / Shift+Tab 翻页
    # - { when: has_menu, accept: Shift+Tab, send: Page_Up }
    # - { when: has_menu, accept: Tab, send: Page_Down }
    # Option/Alt + ←/→ 切换光标至下/上一个拼音
    - { when: composing, accept: ";", send: "2" }
    - { when: composing, accept: Alt+Left, send: Shift+Left }
    - { when: composing, accept: Alt+Right, send: Shift+Right }
    # emacs_editing:
    - { when: composing, accept: Control+p, send: Left }
    - { when: composing, accept: Control+n, send: Right }
    # 实现无论在 macos 系统中还是在 emacs 内部都可以使用 C-p 与 C-n 来实现选词。
    # macos 系统使用下面两行将 rime 加载好(系统只会加载rime配置一次)，然后再注释掉，emacs 使用上面的配置。
    - { when: composing, accept: Up, send: Left }
    - { when: composing, accept: Down, send: Right }
    # numbered_mode_switch:
    # - { when: always, select: .next, accept: Control+Shift+1 }                  # 在最近的两个方案之间切换
    # - { when: always, select: .next, accept: Control+Shift+exclam }             # 在最近的两个方案之间切换
    # - { when: always, toggle: ascii_mode, accept: Control+Shift+2 }             # 切换中英
    # - { when: always, toggle: ascii_mode, accept: Control+Shift+at }            # 切换中英
    # - { when: always, toggle: full_shape, accept: Control+Shift+5 }             # 切换全半角
    # - { when: always, toggle: full_shape, accept: Control+Shift+percent }       # 切换全半角

    # emacs_editing:
    # - { when: composing, accept: Control+p, send: Up }
    # - { when: composing, accept: Control+n, send: Down }
    # - { when: composing, accept: Control+b, send: Left }
    # - { when: composing, accept: Control+f, send: Right }
    # - { when: composing, accept: Control+a, send: Home }
    # - { when: composing, accept: Control+e, send: End }
    # - { when: composing, accept: Control+d, send: Delete }
    # - { when: composing, accept: Control+k, toggle: xxxxx } #释放Ctrl+k=ctrl+del 万象用来调序，且删除属于低频场景，建议双手操作
    # - { when: composing, accept: Control+h, send: BackSpace }
    # - { when: composing, accept: Control+g, send: Escape }
    # - { when: composing, accept: Control+bracketleft, send: Escape }
    # - { when: composing, accept: Control+y, send: Page_Up }
    # - { when: composing, accept: Alt+v, send: Page_Up }
    # - { when: composing, accept: Control+v, send: Page_Down }

    # optimized_mode_switch:
    # - { when: always, accept: Control+Shift+space, select: .next }
    - { when: always, accept: Shift+space, toggle: ascii_mode }
#+end_src
* Install Librime
** how to get librime on mac?
- from offical: https://github.com/rime/librime
- from elpa: M-x install-package rime
unzip rime-1.5.3-osx.zip -d ~/.emacs.d/librime
** how to get librime on windows?
on window we need [[https://scoop.sh/]].After that [[https://github.com/DogLooksGood/emacs-rime/blob/master/INSTALLATION.org][install librime]]
* Rime Usage
[[https://github.com/DogLooksGood/emacs-rime][Emacs Rime]] which makes to embedding an input method be possible whthin the emacs.Emacs could benefit form the flexible configuration of [[https://rime.im/][rime]].
On macos it's required to install *Squirrel* which is one of rime's distribution. *Squirrel* is installed in your os system as a input method.
Note that the configuration of rime located at home/Library/Rime/. We want to sharing this configuration between Eamcs rime and os rime.
So there have a variable which named ~rime-user-data-dir~ , And another important variable is ~rime-librime-root~ which configed the librime location.
| variable           | required |
| rime-user-data-dir | true     |
| rime-librime-root  | true     |
** 小鹤音形
[[https://www.flypy.com/][小鹤音形]] was a wonderful input method, with it we could touch typing totally. The config file located here [[https://github.com/vanniuner/neo-emacs/tree/master/neoemacs/rime-config][flypy-rime-config]] provided two input method configuration. You need unzip them to ~rime-user-data-dir~ , and config the priority for candidate by ~flypy_top.txt~ .
** Key-binding
| key | binding             |
| C-; | toggle-input-method |
|     | rime-sync           |
|     | rime-deploy         |
** Q/A
- https://github.com/DogLooksGood/emacs-rime supply this plugin.
- https://github.com/rime/plum for more infomation.
- 'emacs-module.h' file not found
 #+begin_src shell
  lib.c:23:10: fatal error: 'emacs-module.h' file not found
    #include <emacs-module.h>
            ^~~~~~~~~~~~~~~~
 #+end_src

 #+begin_src shell
 cp /opt/homebrew/opt/emacs-plus@29/include/emacs-module.h ~/.doom.d/neoemacs/rime-macos/dist/include
 #+end_src
