#+title: rime package readme
#+author: vanniuner
#+SETUPFILE: ~/.doom.d/org-head.setup

* Use system input rime 
Use system input method get a more unify experience, the control chain like C-; -hammerspoon-> shift space -> switch rime ascii.
** hammerspoon
use hammerspoon to switch input method on macos
- `hs.keycodes.currentSourceID("im.rime.inputmethod.Squirrel.Hans")` to rime Squirrel
- `hs.keycodes.currentSourceID("com.apple.keylayout.ABC")` to en 

config hammerspoon 
- in Emacs C-; -> shift-space
- other C-; -> C-z
  
config file：
#+begin_src lua
hs.hotkey.bind({"ctrl"}, ";", function()
    local win = hs.window.frontmostWindow()
    if win then
        local appName = win:application():name()
        if appName == "Emacs" then
            hs.eventtap.keyStroke({"shift"}, "space")
        else
            hs.eventtap.keyStroke({"ctrl"}, "z")
        end
    end
end)
#+end_src

** rime config
- 配置不显示中英文弹框
- 配置 ; 选择第二个词
- 配置 C-p 选择下一个候选项
- 配置 C-n 选择上一个候选项
- 配置 C-h 删除上一个单词
- 配置 Shift+space 选择切换中英输入法
- 配置每次切换后都重置输入法, reset: false 则会记住历史中英模式。因为emacs中经常会切换至minibuffer ，而minibuffer以英文输入情况居多，据切换后强制设置为英文模式.
  
配置：
#+begin_src yaml
# options: always | never | appropriate
show_notifications_when: never

# 快捷键
key_binder:
  bindings:
    - { when: composing, accept: ";", send: "2" }
    - { when: composing, accept: Control+p, send: Left }
    - { when: composing, accept: Control+n, send: Right }
    - { when: composing, accept: Control+h, send: BackSpace }
    - { when: always, accept: Shift+space, toggle: ascii_mode }
    
patch:
  switches:
    - name: ascii_mode
      reset: true
#+end_src

** emacs config
- 配置切换输入法的函数
- 针对rime的entry和exit切换输入法
- 针对minibuffer的setup和exit切换输入法
  
配置：
#+begin_src lisp
(defun my/mac-switch-to-abc ()
  (interactive)
  (start-process
   "hs-abc"
   nil
   "hs"
   "-c"
   "hs.keycodes.currentSourceID(\"com.apple.keylayout.ABC\")"))

(defun my/mac-switch-to-rime ()
  (interactive)
  (start-process
   "hs-rime"
   nil
   "hs"
   "-c"
   "hs.keycodes.currentSourceID(\"im.rime.inputmethod.Squirrel.Hans\")"))

(with-eval-after-load 'evil
  (add-hook 'evil-insert-state-entry-hook #'my/mac-switch-to-rime)
  (add-hook 'evil-insert-state-exit-hook #'my/mac-switch-to-abc)
  (add-hook 'minibuffer-setup-hook #'my/mac-switch-to-rime)
  (add-hook 'minibuffer-exit-hook #'my/mac-switch-to-abc))
#+end_src
* Install Librime
** how to get librime on mac?
- from offical: https://github.com/rime/librime
- from elpa: M-x install-package rime
unzip rime-1.5.3-osx.zip -d ~/.emacs.d/librime
** how to get librime on windows?
on window we need [[https://scoop.sh/]].After that [[https://github.com/DogLooksGood/emacs-rime/blob/master/INSTALLATION.org][install librime]]
* Rime Usage
[[https://github.com/DogLooksGood/emacs-rime][Emacs Rime]] which makes to embedding an input method be possible whthin the emacs.Emacs could benefit form the flexible configuration of [[https://rime.im/][rime]].
On macos it's required to install *Squirrel* which is one of rime's distribution. *Squirrel* is installed in your os system as a input method.
Note that the configuration of rime located at home/Library/Rime/. We want to sharing this configuration between Eamcs rime and os rime.
So there have a variable which named ~rime-user-data-dir~ , And another important variable is ~rime-librime-root~ which configed the librime location.
| variable           | required |
| rime-user-data-dir | true     |
| rime-librime-root  | true     |
** 小鹤音形
[[https://www.flypy.com/][小鹤音形]] was a wonderful input method, with it we could touch typing totally. The config file located here [[https://github.com/vanniuner/neo-emacs/tree/master/neoemacs/rime-config][flypy-rime-config]] provided two input method configuration. You need unzip them to ~rime-user-data-dir~ , and config the priority for candidate by ~flypy_top.txt~ .
** Key-binding
| key | binding             |
| C-; | toggle-input-method |
|     | rime-sync           |
|     | rime-deploy         |
** Q/A
- https://github.com/DogLooksGood/emacs-rime supply this plugin.
- https://github.com/rime/plum for more infomation.
- 'emacs-module.h' file not found
 #+begin_src shell
  lib.c:23:10: fatal error: 'emacs-module.h' file not found
    #include <emacs-module.h>
            ^~~~~~~~~~~~~~~~
 #+end_src

 #+begin_src shell
 cp /opt/homebrew/opt/emacs-plus@29/include/emacs-module.h ~/.doom.d/neoemacs/rime-macos/dist/include
 #+end_src
