#+title: ejc-sql readme
#+subtitle: this is subtitle
#+author: vanniuner
#+SETUPFILE: ~/.doom.d/org-head.setup

* Ejc-sql Usage
 - The privacy configuration
   In here you could save any connections in your setting config.
   But where should the setting located especially for our Emacs config project with a public github repository? There have a privacy path which is excluded in the public repository named *user-private-dir*, You could config your connection's account/password here for safely.
 - Config your particular db connection
   #+ATTR_LATEX: :options numbers=left, commentstyle=\color{violet}
   #+begin_src lisp
   (use-package ejc-sql
   :commands ejc-sql-mode ejc-connect
   :config
   (setq clomacs-httpd-default-port 18090)
   (ejc-create-connection "connection-name"
           :classpath      "~/.m2/repository/mysql/mysql-connector-java/8.0.17/
               mysql-connector-java-8.0.17.jar"
           :connection-uri "jdbc:mysql://localhost/user?useSSL=false&user=root&password=pwd"
           :separator      "</?\.*>" )
   )
   (provide 'db-work)
   #+end_src
  #+latex:\newpage
 - Write Sql file
   Before try to use ejc sql, firstly create a sql file which named with a suffix *.sql*, cause emacs will turn on the sql minor mode so that ejc-sql could works well. And then use ~SPC e c~ to connect a particular database which you have configurated. Emacs will popup a minibuffer listing candidates which show you the *connection-name*.
   Secondarily, write your testing sql content which surrounded by a tag, cause we have configurated *:separator* by a syntax meaning tag in order to execute a single sql rather than to choose it.For sure you could make any comment with the tag's schema.
   Further more, you could use delimiter sign for batch execution. the delimiter could customization by any character.
   Finnaly, use ~C-c C-c~ to execute it. It's just execute the content which surrounded by a tag in your cusor.
   #+BEGIN_SRC sql -n
   <SELECT name='select all org'>
   SELECT * FROM TABLE_ORG
   </SELECT>

   <SELECT>
   delimiter ;
   COMMENT ON COLUMN TABLE_ORG.PROJECT_CODE IS '项目编码';
   COMMENT ON COLUMN TABLE_ORG.PERIOD IS '期间';
   </SELECT>
   #+END_SRC
 - key binding
    | <l>     | <l>            | <l>                        |
    | KEY     | FUNCTION       | description                |
    | SPC e c | ejc-connection | choose connection with ivy |
    | C-c C-c | ejc-execute    | execute the sql            |

* Sqlserver
Maybe you need this post for `The server selected protocol version TLS10 is not accepted by client preferences` : https://blog.csdn.net/w605283073/article/details/126755540
